### ISSUE TITLE
DebugLog Compiler Error

### ISSUE THREAD

**Issue by wangshuaidavid** [inamiy/DebugLog#1]
When I drag DebugLog folder into my project , set up everything fine, but when I build and run, is pops up to me two _Swift Compiler Error_

```
/Users/ennrd/EnnPhotoPub/EnnPhotoPub/Vendor/DebugLog/DebugLog.swift:98:20: 'FileReader' is not a member type of 'DebugLog'
```

```
/Users/ennrd/EnnPhotoPub/EnnPhotoPub/Vendor/DebugLog/DebugLog.swift:73:26: 'DebugLog.FileReader' does not have a member named 'readLogLine'
```

How to fix that?  Thanks in advance.

**Comment by inamiy** [comment]
Hi, thank you for feedback.
I updated the project to support Swift 1.2, 
so please use `DebugLog.all.swift` instead as discussed in #2.

**Comment by wangshuaidavid** [comment]
Thanks!  :+1:
