### ISSUE TITLE
LOG_OBJECT should fallback to LOG on Devices

### ISSUE THREAD

**Issue by toshi0383** [inamiy/DebugLog#10]
LOG_OBJECT prints nothing when Debugging on Devices, since DDFileReader cannot get the files to read.
In such case, I thought LOG_OBJECT should fallback to LOG. So we can at least see some output.

Or is there alternative way to make LOG_OBJECT to work on Devices ?

**Comment by inamiy** [comment]
I'm :+1: on this idea!

I don't think there's no good way of `LOG_OBJECT` on device since `DDFileReader` reads source code directly.
