### ISSUE TITLE
Print functionName always by default.

### ISSUE THREAD

**Issue by toshi0383** [inamiy/DebugLog#12]
Though printHandler is totally customisable, I thought functionName should be printed by default.
Currently functionName is not printed when `body` exists.
Did you want me to submit a PR to address this functionality?

**Comment by inamiy** [comment]
Since I have never seen any other logging libraries which _always_ prints functionName, I'm not positive on this proposal :confused:
I think user-customization is enough.

**Comment by toshi0383** [comment]
I see. That's understandable.😉
Will close this one.
